services:
  rag-app:
    user: "${UID}:${GID}"
    build: .
    network_mode: host
    # ports:
    #   - "8000:8000"
    volumes:
      - ./app/data/docs:/app/data/docs
      - ./app/vector_db/chroma_store:/app/app/vector_db/chroma_store
    environment:
      - LLM_BASE_URL_KEY=http://localhost:11434
      - PYTHONPATH=/home/appuser/.local/lib/python3.11/site-packages
      - PATH=$PATH:/home/appuser/.local/bin
      - PYTHONUNBUFFERED=1y
    depends_on:
      - ollama

  ollama:
    network_mode: host
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 900s
    entrypoint: >
      sh -c '
        ollama serve &
        SERVER_PID=$!
        sleep 2
        ollama pull phi3:mini
        wait $SERVER_PID
      '
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://rag-app:8000
    depends_on:
      - rag-app
    restart: unless-stopped

volumes:
  ollama_data:
